### PR TITLE
Recordings of La Crosse LTV-W1

### PR DESCRIPTION
**Pull request by BarryMar**
These recordings were from an LTV-W1 (Sensor ID: 0FB220) and LTV-TH2 (Sensor ID: 13EFB7)

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
I've updated the commit, these were all TH2
- g002_915M_1000k.cu8: {250}555555555555555a5545ba827df6e0c48c06203a5a5a5a5a400000000000000
- g004_915M_1000k.cu8: {250}555555555555555a5545ba827df6e1048c06229a5a5a5a5a400000000000000
- g009_915M_1000k.cu8: {250}555555555555555a5545ba827df6e1c48e062e7a5a5a5a5a400000000000000
- g010_915M_1000k.cu8: {250}555555555555555a5545ba827df6e0048e062cda5a5a5a5a400000000000000
- g011_915M_1000k.cu8: {250}555555555555555a5545ba827df6e0448e062c3a5a5a5a5a400000000000000

e.g.
- `d2aa2dd4 13efb7 0624603101d2d2d2d2d200000000000000`
- `d2aa2dd4 13efb7 0824603114d2d2d2d2d200000000000000`
- `d2aa2dd4 13efb7 0e24703173d2d2d2d2d200000000000000`
- `d2aa2dd4 13efb7 0024703166d2d2d2d2d200000000000000`
- `d2aa2dd4 13efb7 0224703161d2d2d2d2d200000000000000`

The W1 is in 
- g007_915M_1000k.cu8: {234}555555555555555a5545ba81f6440015555540015559c00000000000000

Data is
- `d2aa2dd4 0fb220 00aaaaaa000aaace00000000000000`

That data looks "empty", it's received correct though:
ltv-w1

**Comment by zuckschwerdt** [comment]
Can you run with
`rtl_433 -f 915M -s 1M -R 0 -X 'n=LTV-W1,m=FSK_PCM,s=100,l=100,r=9000,preamble=d2aa2dd40fb220'`
And write a list of codes with the expected values?

E.g.
{119}00aaaaaa000aaace00000000000000 : wind avg... max...

**Comment by BarryMar** [comment]
rtl_433 -f 915M -S unknown -s 1M -R 0 -X 'n=LTV-W1,m=FSK_PCM,s=100,l=100,r=9000,preamble=d2aa2dd40fb220'

rtl_433 version 21.05-122-g4bb75b4c branch master at 202110291420 inputs file rtl_tcp RTL-SDR
Use -h for usage help and see https://triq.org/ for documentation.
Trying conf file at "rtl_433.conf"...
Trying conf file at "/Users/barrymarshall/.config/rtl_433/rtl_433.conf"...
Trying conf file at "/usr/local/etc/rtl_433/rtl_433.conf"...
Trying conf file at "/etc/rtl_433/rtl_433.conf"...

New defaults active, use "-Y classic -s 250k" for the old defaults!

Disabling all device decoders.
Registered 1 out of 200 device decoding protocols [ ]
Found Rafael Micro R820T tuner
Exact sample rate is: 1000000.026491 Hz
[R82XX] PLL not locked!
Sample rate set to 1000000 S/s.
Tuner gain set to Auto.
Tuned to 915.000MHz.
baseband_demod_FM: low pass filter for 1000000 Hz at cutoff 200000 Hz, 5.0 us
*** Saving signal to file g001_915M_1000k.cu8 (253970 samples, 524288 bytes)
*** Saving signal to file g002_915M_1000k.cu8 (110601 samples, 262144 bytes)
*** Saving signal to file g003_915M_1000k.cu8 (381883 samples, 786432 bytes)

Speed: 0 km   Good battery
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2021-11-10 09:42:59
model     : LTV-W1       count     : 1             num_rows  : 1
rows      : 
len       : 125          data      : 055555550002aabc8000000000000000
codes     : {125}055555550002aabc8000000000000000

Speed: 9 km   Good battery
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2021-11-10 09:43:30
model     : LTV-W1       count     : 1             num_rows  : 1
rows      : 
len       : 119          data      : 0caaaaaa05dad49a00000000000000
codes     : {119}0caaaaaa05dad49a00000000000000

Speed: 13 km   Good battery
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2021-11-10 09:44:02
model     : LTV-W1       count     : 1             num_rows  : 1
rows      : 
len       : 119          data      : 0eaaaaaa07faaafe00000000000000
codes     : {119}0eaaaaaa07faaafe00000000000000
*** Saving signal to file g004_915M_1000k.cu8 (42779 samples, 131072 bytes)

Speed: 12 km   Good battery
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2021-11-10 09:44:33
model     : LTV-W1       count     : 1             num_rows  : 1
rows      : 
len       : 117          data      : 00aaaaaa074aaac800000000000000
codes     : {117}00aaaaaa074aaac800000000000000
*** Saving signal to file g005_915M_1000k.cu8 (308877 samples, 655360 bytes)

Speed: 19 km   Good battery
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2021-11-10 09:45:05
model     : LTV-W1       count     : 1             num_rows  : 1
rows      : 
len       : 120          data      : 02aaaaaa0bfaaaad00000000000000
codes     : {120}02aaaaaa0bfaaaad00000000000000

Speed: 5 km   Good battery
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2021-11-10 09:45:36
model     : LTV-W1       count     : 1             num_rows  : 1
rows      : 
len       : 124          data      : 0255555500d6aa85000000000000000
codes     : {124}0255555500d6aa85000000000000000
*** Saving signal to file g006_915M_1000k.cu8 (42958 samples, 131072 bytes)
*** Saving signal to file g007_915M_1000k.cu8 (42793 samples, 131072 bytes)
*** Saving signal to file g008_915M_1000k.cu8 (57993 samples, 131072 bytes)
*** Saving signal to file g009_915M_1000k.cu8 (381818 samples, 786432 bytes)

Speed: 4 km   Good battery
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2021-11-10 09:46:39
model     : LTV-W1       count     : 1             num_rows  : 1
rows      : 
len       : 120          data      : 08aaaaaa011aaa3900000000000000
codes     : {120}08aaaaaa011aaa3900000000000000

Speed: 2 km   Good battery
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2021-11-10 09:47:11
model     : LTV-W1       count     : 1             num_rows  : 1
rows      : 
len       : 119          data      : 0aaaaaaa000aaaf200000000000000
codes     : {119}0aaaaaaa000aaaf200000000000000
*** Saving signal to file g010_915M_1000k.cu8 (308738 samples, 655360 bytes)

Speed: 0 km   Good battery
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2021-11-10 09:50:20
model     : LTV-W1       count     : 1             num_rows  : 1
rows      : 
len       : 119          data      : 06aaaaaa000aaada00000000000000
codes     : {119}06aaaaaa000aaada00000000000000
^CSignal caught, exiting!

**Comment by BarryMar** [comment]
Since I brought this wind sensor inside to do the previous tests with a hair dryer, here's a bunch of samples of 0 km wind as well if that's helpful.

rtl_433 -f 915M -s 1M -R 0 -X 'n=LTV-W1,m=FSK_PCM,s=100,l=100,r=9000,preamble=d2aa2dd40fb220'

rtl_433 version 21.05-122-g4bb75b4c branch master at 202110291420 inputs file rtl_tcp RTL-SDR
Use -h for usage help and see https://triq.org/ for documentation.
Trying conf file at "rtl_433.conf"...
Trying conf file at "/Users/barrymarshall/.config/rtl_433/rtl_433.conf"...
Trying conf file at "/usr/local/etc/rtl_433/rtl_433.conf"...
Trying conf file at "/etc/rtl_433/rtl_433.conf"...

New defaults active, use "-Y classic -s 250k" for the old defaults!

Disabling all device decoders.
Registered 1 out of 200 device decoding protocols [ ]
Found Rafael Micro R820T tuner
Exact sample rate is: 1000000.026491 Hz
[R82XX] PLL not locked!
Sample rate set to 1000000 S/s.
Tuner gain set to Auto.
Tuned to 915.000MHz.
baseband_demod_FM: low pass filter for 1000000 Hz at cutoff 200000 Hz, 5.0 us
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2021-11-10 10:47:02
model     : LTV-W1       count     : 1             num_rows  : 1
rows      : 
len       : 120          data      : 0eaaaaaa000aaa0500000000000000
codes     : {120}0eaaaaaa000aaa0500000000000000
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2021-11-10 10:50:11
model     : LTV-W1       count     : 1             num_rows  : 1
rows      : 
len       : 118          data      : 0b555554001555e400000000000000
codes     : {118}0b555554001555e400000000000000
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2021-11-10 10:53:20
model     : LTV-W1       count     : 1             num_rows  : 1
rows      : 
len       : 119          data      : 06aaaaaa000aaada00000000000000
codes     : {119}06aaaaaa000aaada00000000000000
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2021-11-10 10:59:38
model     : LTV-W1       count     : 1             num_rows  : 1
rows      : 
len       : 120          data      : 0eaaaaaa000aaa0500000000000000
codes     : {120}0eaaaaaa000aaa0500000000000000
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2021-11-10 11:02:47
model     : LTV-W1       count     : 1             num_rows  : 1
rows      : 
len       : 119          data      : 0aaaaaaa000aaaf200000000000000
codes     : {119}0aaaaaaa000aaaf200000000000000
^CSignal caught, exiting!

**Comment by zuckschwerdt** [comment]
Open an issue "Add support for LTV-W1" on rtl_433 please.

**Comment by BarryMar** [comment]
Can I provide any better recordings for the archive with some different settings?  Or are we good enough?

**Comment by zuckschwerdt** [comment]
Let's build a decoder in merbanan/rtl_433#1855, then add better samples.

**Pull request merged**
