### PR TITLE
Add Toyota PMV-C210 to improve readings

### PR DESCRIPTION
**Pull request by tosiek**

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Thanks! Did you record with default sample rate and frequency? Always try to keep that info around :)

**Comment by tosiek** [comment]
There is example output from my console:

> Using device 0: Generic RTL2832U OEM

> Exact sample rate is: 250000.000414 Hz
> Sample rate set to 250000 S/s.
> Bit detection level set to 0 (Auto).
> Tuner gain set to Auto.
> Reading samples in async mode...
> Tuned to 433.920MHz.
> {"time" : "2018-11-26 15:05:24", "model" : "Toyota", "type" : "TPMS", "id" : "f0b9f6d5", "status" : 160, "pressure_kPa" : 1.724, "temperature_C" : 17.000, "mic" : "CRC"}
> *** a->signal_start = 3400452, a->signal_end = 3477110
> signal_len = 76658,  pulses = 3
> Distance coding: Pulse length 1993
> 
> Short distance: 25318, long distance: 0, packet distance: 25339
> 
> p_limit: 1993
> bitbuffer:: Number of rows: 3
> [00] { 0}           :
> [01] { 0}           :
> [02] { 0}           :
> signal_bsize = 262144  -      sg_index = 786432
> start_pos    = 400618  -   buffer_size = 3145728
> *** Saving signal to file g001_433.92M_250k.cu8
> *** Writing data from 400618, len 262144
> Signal caught, exiting!

**Comment by tosiek** [comment]
Do you need that inof for other readings? I did not close the console window :)

**Comment by zuckschwerdt** [comment]
All I need, thanks. Defaults :)

**Comment by tosiek** [comment]
Are there any unreaded bits left? I could try to simulate other conditions  :)

**Comment by zuckschwerdt** [comment]
See [the BitBench](http://triq.net/bitbench?c=z%20128%20%5Bidle%5D&c=z%20176%20%5Bbattery%20low%5D&c=z%20160%20%5Bwakeup%5D&c=z%20132%20%5Bdeflate%20alarm%5D&f=4b%204b%0Av%0AFIXED%3A1b%20%3F%3A1b%20WAKEUP%3A1b%20BATT_LOW%3A1b%20%3F%3A1b%20ALARM%3A1b%20%3F%3A1b%20%3F%3A1b%0A.) (click ToggleHelp and the "C" to see the most).

We are missing 192, 136, 130, 129, and maybe 0.

**Comment by tosiek** [comment]
Low battery means probably chip reset:
https://www.infineon.com/dgdl/Infineon-SP370-25-116-0-DS-v01_01-EN.pdf?fileId=5546d462625a528f01629624b01d6346
Supply voltage range 1.9…3.6V

There is G: ok on my device. It means G sensor probably.
Without own transmitter simulation read different G status could be impossible, because G sensor  is integrated in the chip and I do not know how to broke it.

Are there any module for Arduino which can send data like TPMS? What modulation need to be supported? I found  SX1278 Module DRF1278F with supported Modulation: FSK/GFSK/MSK/LoRa and library for this chip. 

Now i have only dummy transmitter FS100A and receiver 433 MHz XY-MK. It is fine only for fixed code transmissions.

Is it possible to sniff 115kHz wake up signal with rtl_433 and rtl _sdr device?

**Comment by zuckschwerdt** [comment]
RTL-SDR can not tune that low (24 MHz – 1766 MHz). Sending will be really complicated. I don't think the usual Arduino devices will work reliably.
About the G-sensor, do you have the sensor unmounted? Perhaps you can spin it on a power drill?

**Comment by zuckschwerdt** [comment]
If you can get a PlutoSDR you can resend the signals. I made a software for that. https://github.com/zuckschwerdt/tx_tools/

Otherwise I have a CC1101 (RF1100se module) connected to a Raspi, maybe I can write a software to send with that. But it won't be easy and you need to know much about the CC1101 and hardware.

**Comment by tosiek** [comment]
I found this guy. He send tpms spoof signal for subaru with CC1101:
https://github.com/JoeSc/Subaru-TPMS-Spoofing

And there is another case study:
http://www.winlab.rutgers.edu/~Gruteser/papers/xu_tpms10.pdf

**Comment by tosiek** [comment]
You could use raspi to send:
https://github.com/F5OEO/rpitx

**Comment by tosiek** [comment]
And the last one, build pseduo tpms transmitter:
https://web.wpi.edu/Pubs/E-project/Available/E-project-030416-121729/unrestricted/MQP_Final_Paper.pdf

Wirelles world is awesome! zuckschwerdt thank you for your hard work!

**Comment by zuckschwerdt** [comment]
I'm going to write a general TPMS sender using the CC1101 (rf1100se module) for the Raspi. Will take a week or so. Sending TMPS signals using the PlutoSDR already works -- I can provide an example if anybody is interested.

**Comment by merbanan** [comment]
I had the idea for a generic OOK/FSK transmitter based on these components:

https://www.ebay.com/itm/CC1101-STM8-Testing-Board-E06-TB07-with-Micro-USB-Interface-for-Ebyte-E07-Module/192222922237?hash=item2cc16105fd:g:5mcAAOSwNMVaTtaC:rk:85:pf:0

https://www.ebay.com/itm/E07-M1101D-TH-10dBm-Wireless-Transceiver-433MHz-CC1101-SPI-Module-Spring-Antenna/191974909018?hash=item2cb298a45a:g:aQgAAOSw4LdbZAO0:rk:162:pf:0

but I never got the time to complete the firmware. And the serial interface is tricky to design correctly.

**Comment by zuckschwerdt** [comment]
A Raspi is the easiest way to control pins, with just a few lines Python even. But having a neat compact device would be great. I guess it could reasonably be CC1101 + ESP32 to have a well-supported platform.

**Comment by merbanan** [comment]
@tosiek Regarding 125kHz signals if it is possible to open the activator device and tap the data pins you can get to the activator signals for the TPMS sensors. I have been working on the rdm6300 as a generic 125kHz device. But I never completed the firmware for generic signal transmission.

**Comment by merbanan** [comment]
@zuckschwerdt I'd like to hit the same price point as a rtl-sdr but for OOK/FSK signal transmission. It is easy for me to build something custom but I would like to get to a solution that anyone can adapt to and build upon. A usb interfaced transmitter would be best but I have never found good enough hardware.

https://www.ebay.com/itm/HC-12-USB-CC1101-433Mhz-Wireless-Serial-Port-Module-Wireless-Module-for-Arduino/201725104033?hash=item2ef7c0cfa1:g:L~cAAOSwytJZ5uJL:rk:22:pf:0

https://www.ebay.com/itm/CC1101-USB-433Mhz-Wireless-RF-Transceiver-Module-10mW-USB-UART-MAX232-RS232/282661596556?hash=item41cff1ad8c:g:Lx8AAOSwM7JZwi1H:rk:24:pf:0

Those devices are nice but it is hard to reprogram them. I found the first device several years ago. If they only had ordinary 2.54 pitch for the programming pads I could have sold them thousands of devices.

**Comment by merbanan** [comment]
@tosiek forgot to say that a logic analyzer could be used to tap the data pins. The activator signal is turning on and off the carrier coil in a specific pattern. When you have the pattern it is possible to replicate it.

**Comment by zuckschwerdt** [comment]
I guess custom hardware would be about twice the price of ready-made or tailored transmitter. The ESP32+CC1101 (at 15 EUR including a usable antenna, need to solder 7 pins, power can work over USB) would offset that maybe by the open and easy programming (also dual-core, capable RTOS, and an active community).
But then again, if you had a STM8+CC1101 kit with firmware I'd buy that on the spot :)

**Comment by tosiek** [comment]
SDR with TX are too expensive for hobbyists. For example:
HackRF One - 300$
ADALM-PLUTO - 150$

CC1101 has library for Arduino and Raspi:  https://github.com/SpaceTeddy/CC1101 
Will this library support custom packets?

For standalone device and most universal HC-12 would be nice choice (of course if it support hardware part tha we need). There is a module controlled via UART. You can use simple USB - UART for pc. You can control it with arduino, raspi and others uC with UART support. Even make passthrough via Arduino to PC (probably) :) 
I do not know that AT commands is enough for this purpose:
http://trainelectronics.com/Arduino/HC-12-Serial_Radio/images/HC-12%20v2.3A.pdf
https://www.elecrow.com/download/HC-12.pdf
or just use this device from ebay HC-12-USB.

There is a software to inital config HC-12 via pc:
http://trainelectronics.com/Arduino/HC-12-Serial_Radio/

Software on pc + HC-12 will be nice.


I must not open the TPMS device, sorry. 

But there is a reason why I like Arduino community, someone write a Logic analyzer:
https://github.com/aster94/logic-analyzer
I have read chineese ultrasonic parking sensors with it.

**Comment by tosiek** [comment]
He used stlink for programing HC-12 (STM8S003F3P6 ) and made spectrum analyzer. There is no source code.
https://hackaday.io/project/27319-432-434mhz-range-spectrum-analyzer-based-on-hc-12
We could try to update soft with AT+UPDATE.

**Comment by merbanan** [comment]
I looked into that. It uses a si446x chip. Not the CC1101. And the firmware update format is not know also.

**Comment by zuckschwerdt** [comment]
What's the bandwidth (sample rate) on the Arduino hack? If you need a inexpensive Logic Analyzer look at the [Saleae 8ch 24MHz clones](https://sigrok.org/wiki/Supported_hardware#Logic_analyzers), i got mine for ~8 EUR.
I got an ADALM-PLUTO at the introduction price of 85 EUR, current 150 seems expensive.

**Comment by merbanan** [comment]
I just realized that with a clipon adapter it would be possible to program the atmel8 on the CC1101-USB-433Mhz-Wireless-RF-Transceiver device. Flash a suitable arduino bootloader and it would be a really user friendly device.

**Comment by tosiek** [comment]
@merbanan Do yo mean RM1101-USB-232?
https://imgur.com/eJ0kDmf.jpg
Are you sure there is atmel not stm?

**Comment by merbanan** [comment]
The version I bought several years ago was atmel. The pcb inside could have changed.

Anyway I found the device I would have needed for this.
https://hobbyking.com/en_us/atmel-atmega-socket-firmware-flashing-tool.html
Unfortunately not available any more.

**Comment by tosiek** [comment]
There is ATmega48PA. There is feedback with low resolution photos:
https://www.aliexpress.com/item/433Mhz-CC1101-USB-Wireless-RF-Transceiver-Module-10mW-USB-UART-MAX232-RS232-Low-Power-Transparent-Data/32877048266.html
He used SmartRF Studio.

It would be easier to solder programmed chip :)

**Comment by merbanan** [comment]
https://www.ebay.com/itm/ESC-Flashing-Programming-Tool-Socket-Flash-AVR-Atmel-Atmega-AU-32-chip-KIT/323490964029?hash=item4b5190623d:g:-M0AAOSwVxtbGzYR

or tests clips will probably work.

**Comment by merbanan** [comment]
https://photos.google.com/share/AF1QipMpfEO9r4cuf6pPU8QaG8dW27-molUh9fGWVRdaGxZMS2KPhpV8mQ82tv-nXqh3QQ?key=UjVveWxreWhYLXZHZXdMdUw1b1Z3RVFmMG94YU13

**Comment by merbanan** [comment]
I had breadboard jumper cables with round tips.

https://www.ebay.com/itm/65Pcs-Male-to-Male-Solderless-Flexible-Breadboard-Jumper-Cable-Wires-For-Arduino/252107574004?epid=1066101990&hash=item3ab2c84af4:g:JBUAAOSwv0tVAV2q:rk:10:pf:0

They fit perfectly into the small vias of the board. I think we have a winner.

**Comment by tosiek** [comment]
Is it test points for ICSP programming? Which legs are connected?

**Comment by merbanan** [comment]
MISO/MOSI/SCK are the 3 close to each other. The lone one is the RESET. GND and VCC have other points.

**Comment by merbanan** [comment]
I was able to reset the atmega but got no data from it. I used a test clip to connect directly to the reset pin.

**Comment by merbanan** [comment]
I think I need pro tips to get this working.

**Comment by merbanan** [comment]
I think the reset pin is disabled. But it might be a clocking issue also. Think this needs a HV programmer to bring alive.

**Comment by merbanan** [comment]
There is a fuse to disable the RESET pin. I suspect that it is set. I have another device that is the same but without the usb bridge. I can not connect to that either. And then I tried the 2 other boards that worked fine. So something with the 8MHz external crystal or the RESET pin is disabled (set to IO mode).

**Comment by tosiek** [comment]
stk500 clone probably allow high voltage. But it will be easier to solder new chip with programmed bootloader :)

Why don't you use just arduino with cc1101 for prototyping then you can migrate code to atmel8 and solder programmed chip or try in cirucit programming with weird adapters? :)

**Comment by merbanan** [comment]
The target was an off the shelf device for like $10-$15. This device has everything except an easy programmable mcu.

**Comment by tosiek** [comment]
There is a shield for arduino HV programming:
https://mightyohm.com/blog/products/hv-rescue-shield-2-x/
There is diy version:
https://mightyohm.com/blog/2008/09/arduino-based-avr-high-voltage-programmer/

There is no easy way to program in circuit if ISP is not set. We need access to almost all the pins i did not see that kind of adapter to in circuit programming for tqfp 32 (you linked before for only isp).

The only way is to unsolder chip, programm and solder again:
https://imgur.com/ChUzZIy

Or just use arduino + cc1101 :) It is kind off the shelf device.

**Comment by tosiek** [comment]
They sold cul devices but it cost 49Euro:
http://shop.busware.de/product_info.php/products_id/44

**Comment by tosiek** [comment]
Ther is another All in one: Kyl-220 with unknown and probably unprogrammable MCU:
https://www.aliexpress.com/item/Wireless-USB-RF-Transmitter-Receiver-200m-400m-RF-range-High-Speed-upto-100kbps-with-MCU/32780156086.html

The best way is USB-UART-TRANSCEIVER (or just transmitter) wihout MCU.

Out ouf the box is for me usb-uart (like ch341 about 0,8$) and HC-11 with uart communication. We will need then just pc software.

There is something like that but with sv610:
https://pl.aliexpress.com/item/8pcs-package-SV610-100mW-TTL-interface-433MHz-wireless-transceiver-module-8pcs-copper-spring-antenna-1pcs-TTL/32347151787.html
Datascheet for sv610:
http://webcache.googleusercontent.com/search?q=cache:sbmGR4OKiLYJ:nicerf.com/Upload/20160920/160920050414.pdf+&cd=1&hl=pl&ct=clnk&gl=pl&client=firefox-b-ab

**Comment by tosiek** [comment]
I read some datasheest. We cannot use CC1101 with UART because all of them has implemented algorithm for sending data. We have to use SPI version.

**Comment by zuckschwerdt** [comment]
@tosiek if we assume the identified low battery flag to actually mean chip reset, can you perhaps test where the battery_low flag is? Do you have a known flat battery to test or better a variable power supply which you could drop to 1.8V?

**Comment by tosiek** [comment]
I have connected TPMS to regulated power supply. Tested voltage 3.3V, 3.0V 2.5V, 2.0V, 1.9V and 1.7 and 1.8. (below 1.6 it does not work).

Only below 1.9V when i wake up device with Ateq VT55 status changed to 176 (from 160 with wake) but Ateq always shows Batt: OK - even on 1.8.

So i'm not sure what flag is it because chip work by datasheet on 1.9V to 3.6V. 
It could be flag first run or even 433 RF failure. (below 2.5V pressure sensor stopped working but below 1.9 RF and somehting else stop working i could not find this table).

**Comment by tosiek** [comment]
There is a voltage operating table:
https://imgur.com/a/PhZc5X6

**Pull request merged**
