### PR TITLE
Honda car remote captures causing segmentation faults.

### PR DESCRIPTION
**Pull request by ukshady**
Just added captures for Honda car remote which is not decoding as its causing segmentation faults.
Also added Nexus temp/humidity sensor which is decoding okay.

### CODE REVIEW

**Comment by merbanan** [comment]
Thanks

**Comment by merbanan** [comment]
Can you give a command line that causes segmentation fault ?

**Comment by ukshady** [comment]
~/rtl_433_tests/tests/honda_remote/01 $ rtl_433 -r hondacar-unlock.data
Registering protocol "Silvercrest Remote Control"
Registering protocol "Rubicson Temperature Sensor"
Registering protocol "Prologue Temperature Sensor"
Registering protocol "Waveman Switch Transmitter"
Registering protocol "Steffen Switch Transmitter"
Registering protocol "ELV EM 1000"
Registering protocol "ELV WS 2000"
Registering protocol "LaCrosse TX Temperature / Humidity Sensor"
Registering protocol "Acurite 5n1 Weather Station"
Registering protocol "Acurite 896 Rain Gauge"
Registering protocol "Acurite Temperature and Humidity Sensor"
Registering protocol "Oregon Scientific Weather Sensor"
Registering protocol "Mebus 433"
Registering protocol "Intertechno 433"
Registering protocol "KlikAanKlikUit Wireless Switch"
Registering protocol "AlectoV1 Weather Sensor (Alecto WS3500 WS4500 Ventus W155/                                                                 W044 Oregon)"
Registering protocol "Cardin S466-TX2"
Registering protocol "Fine Offset Electronics, WH-2 Sensor"
Registering protocol "Nexus Temperature & Humidity Sensor"
Registering protocol "Ambient Weather Temperature Sensor"
Registering protocol "Calibeur RF-104 Sensor"
Registering protocol "X10 RF"
Registering protocol "DSC Security Contact"
Registering protocol "Brennstuhl RCS 2044"
Registering protocol "GT-WT-02 Sensor"
Registering protocol "Danfoss CFR Thermostat"
Registering protocol "Energy Count 3000 (868.3 MHz)"
Registering protocol "Valeo Car Key"
Registering protocol "Chuango Security Technology"
Test mode active. Reading samples from file: hondacar-unlock.data
Segmentation fault

**Comment by ukshady** [comment]
I went through each protocol and found the segmentation fault happens on just these two devices  
~/rtl_433_tests/tests/honda_remote/01 $ rtl_433 -R 27 -r hondacar-unlock.data
Registering protocol "Energy Count 3000 (868.3 MHz)"
Test mode active. Reading samples from file: hondacar-unlock.data
Segmentation fault

 rtl_433 -R 26 -r hondacar-unlock.data
Registering protocol "Danfoss CFR Thermostat"
Test mode active. Reading samples from file: hondacar-unlock.data
Segmentation fault

**Comment by vestom** [comment]
Segmentation fault was due to a couple of bugs in the FSK decoder, causing a memory overflow of the pulse structure.
Fixed in: https://github.com/merbanan/rtl_433/pull/155

**Comment by vestom** [comment]
The hondacar-lock.data is a bit too low level for proper detection, but the other files work fine.
Example: 
```
$ rtl_433 -A -r rtl_433_tests/tests/honda_remote/01/hondacar-lock2.data
Test mode active. Reading samples from file: /home/tov/trysdr/rtl_433_tests/tests/honda_remote/01/hondacar-lock2.data
Detected FSK package
Analyzing pulses...
Total number of pulses: 394
Pulse width distribution:
 [ 0] mean:   62 [61;66],	 count: 364
 [ 1] mean:  123 [122;124],	 count:  29
 [ 2] mean:    5 [5;5],	 count:   1
Gap width distribution:
 [ 0] mean:   62 [61;64],	 count: 363
 [ 1] mean:  124 [123;126],	 count:  29
 [ 2] mean:   19 [19;19],	 count:   1
Pulse period distribution:
 [ 0] mean:  124 [122;130],	 count: 363
 [ 1] mean:  247 [245;249],	 count:  29
 [ 2] mean:   81 [81;81],	 count:   1
Guessing modulation: Pulse Width Modulation with startbit/delimiter
Attempting demodulation... short_limit: 33, long_limit: 92, reset_limit: 127, demod_arg: 0
pulse_demod_pwm_ternary(): Analyzer Device 
bitbuffer:: Number of rows: 2 
[00] {393} 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0f 59 08 98 24 a5 53 e9 05 00 
[01] {0} : 
```

**Pull request merged**
