### PR TITLE
"Emax" branded remote control tests

### PR DESCRIPTION
**Pull request by salleq**
Hopefully provided enough information about this.

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Thanks!

**Comment by salleq** [comment]
Hey, I noticed that the remote sends 2 rows of some kind of initialization pulses, before it sends the command itself. For some reason it doesn't get saved on rtl_433 -S unknown. How would I save those in a file?

When I run rtl_433 -A -a 4 I can see those initial messages as well but they're not saved?

**Comment by zuckschwerdt** [comment]
Likely a wakeup. Try the timed (no evented) recording, something like: `-w filename_433.92M_250k.cu8 -T 30`

**Comment by salleq** [comment]
Sorry, I think I'm messing something up.

Pressing one button (A "on") I get this message 8 times (using rtl_433 -A -a  4)

```
Detected OOK package    2021-05-13 21:21:36
Analyzing pulses...
Total count:   34,  width: 37.76 ms             ( 9440 S)
Pulse width distribution:
 [ 0] count:   15,  width:  832 us [828;848]    ( 208 S)
 [ 1] count:   19,  width:  316 us [312;324]    (  79 S)
Gap width distribution:
 [ 0] count:   15,  width:  296 us [296;308]    (  74 S)
 [ 1] count:   18,  width:  812 us [808;820]    ( 203 S)
Pulse period distribution:
 [ 0] count:   33,  width: 1132 us [1124;1144]  ( 283 S)
Level estimates [high, low]:  15961,    374
RSSI: -0.1 dB SNR: 16.3 dB Noise: -16.4 dB
Frequency offsets [F1, F2]:    3929,      0     (+15.0 kHz, +0.0 kHz)
Guessing modulation: Pulse Width Modulation with fixed period
Attempting demodulation... short_width: 316, long_width: 832, reset_limit: 824, sync_width: 0
Use a flex decoder with -X 'n=name,m=OOK_PWM,s=316,l=832,r=824,g=0,t=204,y=0'
pulse_demod_pwm(): Analyzer Device
bitbuffer:: Number of rows: 1
[00] {34} 4a f6 f0 4b c0 : 01001010 11110110 11110000 01001011 11
```

After the eight repeated similar messages (with only small variation between times which I believe is expected), I get this message which is shown only once:

```
*** signal_start = 23406648, signal_end = 23519791, signal_len = 113143, pulses_found = 272
Iteration 1. t: 143    min: 79 (152)    max: 208 (120)    delta 13
Iteration 2. t: 143    min: 79 (152)    max: 208 (120)    delta 0
Pulse coding: Short pulse length 79 - Long pulse length 208

Short distance: 74, long distance: 203, packet distance: 2522

p_limit: 143
bitbuffer:: Number of rows: 8
[00] {34} b5 09 0f b4 00 : 10110101 00001001 00001111 10110100 00
[01] {34} b5 09 0f b4 00 : 10110101 00001001 00001111 10110100 00
[02] {34} b5 09 0f b4 00 : 10110101 00001001 00001111 10110100 00
[03] {34} b5 09 0f b4 00 : 10110101 00001001 00001111 10110100 00
[04] {34} b5 09 0f b4 00 : 10110101 00001001 00001111 10110100 00
[05] {34} b5 09 0f b4 00 : 10110101 00001001 00001111 10110100 00
[06] {34} b5 09 0f b4 00 : 10110101 00001001 00001111 10110100 00
[07] {34} b5 09 0f b4 00 : 10110101 00001001 00001111 10110100 00

```

The hexadecimals are different from the original messages, so I don't know what that means? Is this just some kind of summary of the previous messages? If so, the captures I've committed should be ok.

**Pull request merged**
