### PR TITLE
TPMS Nissan Leaf

### PR DESCRIPTION
**Pull request by gcormier**
Honestly, I'm not too sure on the exact hardware inside. I did a lot of research and came up with conflicting information of course. At first I thought it would be ASK, but in fact this one is FSK. It is at 315MHz. The unit in question also does not talk while stationary, I believe it transmits every 10h when no moving.

In any case, some work so far:

[Nissan TPMS on bitbench](http://triq.net/bitbench?c=%5B-X%20%22name%3Dtest%2Cmodulation%3DFSK_PCM%2Cs%3D120%2Cl%3D120%2Cs%3D120%2Cr%3D9000%22%5D&c=&c=7aaaaaaaf554b34ad2b2d4b32ab20%20%5BThis%20was%20captured%20days%20before%20without%20knowing%20I%20had%20it.%20Represents%20the%20highest%20pressure%20before%20any%20deflations%5D&c=&c=7aaaaaaaf354b34ad2b2d4b2d3540%20%5BDeflate%5D%20%5BTemp%20was%2025c%5D&c=7aaaaaaaf354b34ad2b2d4b2d2b20%20%5BDeflate%5D&c=7aaaaaaaf354b34ad2b2d4b2ccd20%20%5BDeflate%5D&c=7aaaaaaaf354b34ad2b2d4b2b52a0%20%5BDeflate%5D&c=7aaaaaaaf354b34ad2b2d4b2b34a0%20%5BDeflate%5D&c=7aaaaaaaf354b34ad2b2d4b2b2b40%20%5BDeflate%5D&c=7aaaaaaaf354b34ad2b2d4b2acd40%20%5BDeflate%5D%20%5BTemp%20was%2025c%5D&c=&c=7aaaaaaaf4d4b34ad2b2d4b2ad340%20%5BReport%5D%20%5BTemp%20was%2025c%5D&c=7aaaaaaaf4d4b34ad2b2d4b2ad340%20%5BReport%5D&c=7aaaaaaaf4d4b34ad2b2d4b2ad520%20%5BReport%5D&c=7aaaaaaaf4d4b34ad2b2d4b2ad520%20%5BReport%5D&c=7aaaaaaaf4d4b34ad2b2d4b2ad520%20%5BReport%5D%20%5BTemp%20was%2025c%5D&c=&c=%5BRound%202%5D&c=7aaaaaaaf354b34ad2b2d4b2aaca0%20%5BDeflate%5D&c=&c=7aaaaaaaf4d4b34ad2b2d4ad54ca0%20%5Bg004%20-%20Just%20before%20cooling%5D&c=7aaaaaaaf4d4b34ad2b2d4ad54ca0%20%5Bg007%5D&c=7aaaaaaaf4d4b34ad2b2d4ad55340%20%5Bg008%5D&c=7aaaaaaaf4d4b34ad2b2d4ad55340%20%5Bg010%20coldest%3F%5D&c=&c=7aaaaaaaf4d4b34ad2b2d4ad55340%20%5BFairly%20stable%5D&c=7aaaaaaaf4d4b34ad2b2d4ad54ac0%20%5Bg017%20-%20let%20a%20little%20air%20out%20just%20before%5D&c=7aaaaaaaf4d4b34ad2b2d4ad53540%20%5Bg023%20let%20a%20bit%20more%20air%20just%20before%2C%2023c%3F%5D&c=&c=7aaaaaaaf4d4b34ad2b2d4ad54ac0%20%5Bg052%20-%3E%20Let%20out%20air%5D&c=7aaaaaaaf4d4b34ad2b2d4ad53540%20%5Bg054%20%3D%20result.%5D&c=7aaaaaaaf4d4b34ad2b2d4ad53540%20%5Bg067%20-%3E%20Let%20out%20TINY%20amount%20of%20air%5D&c=7aaaaaaaf4d4b34ad2b2d4ad532a0%20%5Bg069%20%3D%20result%5D&c=&c=7aaaaaaaf4d4b34ad2b2d4ad52b20%20%5Bg083%20-%20Let%20a%20bunch%20of%20air%20out%20to%20reset%20the%20panic%20mode.%20Tire%20on%20balcony%20to%20cool.%5D&c=7aaaaaaaf4d4b34ad2b2d4ad35540%20%5Bg085%5D&c=7aaaaaaaf4d4b34ad2b2d4ad35540%20%5Bg086%20Pressure%20stabilized.%20Time%20for%20cooling.%5D&c=7aaaaaaaf4d4b34ad2b2d4ad352a0%20%5Bg093%5D&c=7aaaaaaaf4d4b34ad2b2d4ad34cc0%20%5Bg116%20around%209%20degrees%20outside%20rubber%5D&c=7aaaaaaaf4d4b34ad2b2d4ad34b20%20%5Bg123%5D&c=7aaaaaaaf4d4b34ed2b2d4ad334a0%20%5Bg150%5D&c=7aaaaaaaf4d4b34ad2b2d4ad332c0%20%5Bg167%5D&c=7aaaaaaaf4d4b34ad2b2d4ad32d20%20%5Bg201%20Rubber%200%20degrees%5D&f=PRE%3A32hh%20MODE%3Ahh%20TPMS_ID%3F%3A32h%20UNKNOWN%3A12h%20PRESSURE%3A24h%20END%3A8h)

MODE must be a panic mode versus regular status reporting. I am not fully convinced this thing can read the temperature.

I'll need to grab my tire gauge sometime to get a PSI value.

### CODE REVIEW

**Comment by gcormier** [comment]
Flex string I am using : "name=test,modulation=FSK_PCM,s=120,l=120,s=120,r=9000"

**Comment by zuckschwerdt** [comment]
That's too much files to include. We need to keep an eye on repo size. Select ~10 interesting files.
For all the other samples preferably collect the raw codes in the README.

**Comment by gcormier** [comment]
Yup, no problem - I wanted to do a dump, once we get a bit closer on the values (looks like we are almost there) I will pick out some of the interesting ones and trim down this PR.

**Comment by zuckschwerdt** [comment]
Could you still trim this to a few (2-5) interesting files so we can regression test?

**Comment by gcormier** [comment]
No longer have access to this car :)

**Comment by merbanan** [comment]
PR reworked, thanks for the files.

**Pull request closed without merging**
