### PR TITLE
WH2303 - All data updated with centre carriers gfiles too

### PR DESCRIPTION
**Pull request by Psynosaur**
All the recordings where redone this time simultaneously with three RTL's so that the center carrier data(01/*.data) is composed of the two sidebanded bits.

### CODE REVIEW

**Comment by merbanan** [comment]
Hi, you need to rebase the PR for me to be able to merge it.

**Comment by Psynosaur** [comment]
Im quite new to git, how would I do this?

**Comment by merbanan** [comment]
git pull --rebase should solve it. If not do a fresh checkout and create a new PR.

**Comment by Psynosaur** [comment]
Should be good to go

**Comment by Psynosaur** [comment]
high, this should be resolved now :) thx

**Comment by merbanan** [comment]
Yupp

**Pull request merged**
