### PR TITLE
SENSOR: GT-WT-02 (ALDI, Globaltronics..)

### PR DESCRIPTION
**Pull request by ludwich66**

### CODE REVIEW

**Comment by merbanan** [comment]
gfiles are needed if it ever is going to lead anywhere.

**Comment by ludwich66** [comment]
Hi Benjamin,

i have tried to add a jpg Picture and a file named gfile003.data.
if this correct - i dont understand the github mechanismn .. :-(

Please tell me when it is OK, else i do it again

ludwich

**Comment by merbanan** [comment]
Hmm, the image seems corrupt. Can you check it again ?

**Comment by ludwich66** [comment]
?? Is the Data.File OK?
I do open the file with a text editor and copied the „cryptic-data“ to the dialog on github.
is this the right way or do i not see an normal import dialog??

ludwich

**Comment by merbanan** [comment]
Ah, no then the file is probably broken also. You should clone the git repo add the files again and then send a new pull request. You might need to look up a git tutorial first.

MvH
Benjamin Larsson

**Pull request merged**
