### PR TITLE
Samples for IKEA Sparsnäs energy meter

### PR DESCRIPTION
**Pull request by slundell**
This PR contains samples for the IKEA Sparsnäs energy meter. It's my first try at capturing samples. If they are not made correctly, please let me know. 

The Sparsnäs is well documented and several decoders exists on github. More info in the readme.

### CODE REVIEW

**Comment by merbanan** [comment]
It looks like it would be possible to calculate parts of the key based on the referenced code.

**Comment by zuckschwerdt** [comment]
I had a brief look at the g002 sample and it's clipping hard. FSK won't work. You need to record at a lower gain. I/Q need to look sinusoidal.
clip

**Comment by zuckschwerdt** [comment]
You don't need to add the `.sr` files. We generate them with the current rtl_433 to check the demod.

**Comment by slundell** [comment]
I have messed a bit with the parameters to get a good clean sine wave. I have reduced gain (from 40 to 21 arbitrary units :) ) I have also tuned to a slightly different frequency which picks the signal up better. 

Using 250kS/s the sine was a bit jagged, so I also took some samples at 1024kS/s.

**Comment by slundell** [comment]
Removed the `.sr` files.

**Comment by zuckschwerdt** [comment]
The samples really look pretty, thanks! Seems like the sender uses GFSK (smooth wave, narrow band, no hard edges) which does not work well with the current FSK decoder in rtl_433. Tuning down `PD_MIN_PULSE_SAMPLES` in https://github.com/merbanan/rtl_433/blob/master/include/pulse_detect.h#L20 might help.

**Comment by merbanan** [comment]
The demodulator is doing its job if you look at a scaled fm signal. It seems like the bit slicer code can't handle continuous-phase FSK.

**Comment by slundell** [comment]
I had to crank `PD_MIN_PULSE_SAMPLES `down to 3 to get a reliable decoding, but it works now!
I imagine that if I use a higher sample rate, I could probably not turn it down that low? rtl_433 prefers 250kS/s right?

I don't know if that is a problem or not, or what can be done about it, but that's totally above my paygrade :) 

I will try to look into the decoding part now.



```

$ rtl_433  -f 867950000 -s 250k -p 62 -g 32 -a -A  -S unknown -X 'n=sparsnas,m=FSK_PCM,s=26,l=26,r=2800,preamble=AAAAAAAAD201'

Detected FSK package    2019-01-14 21:05:06
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2019-01-14 21:05:06
model     : sparsnas     count     : 1             num_rows  : 1             rows      :
len       : 161          data      : 11a16a070ea2dfefe6d5c8d23147e63530e7ac498
codes     : {161}11a16a070ea2dfefe6d5c8d23147e63530e7ac498
Analyzing pulses...
Total count:   61,  width: 5.45 ms              ( 1363 S)
Pulse width distribution:
 [ 0] count:    1,  width:    0 us [0;0]        (   0 S)
 [ 1] count:   37,  width:   24 us [20;28]      (   6 S)
 [ 2] count:    2,  width:   16 us [16;16]      (   4 S)
 [ 3] count:   13,  width:   48 us [40;56]      (  12 S)
 [ 4] count:    4,  width:   76 us [76;76]      (  19 S)
 [ 5] count:    3,  width:  180 us [156;208]    (  45 S)
 [ 6] count:    1,  width:  100 us [100;100]    (  25 S)
Gap width distribution:
 [ 0] count:    1,  width:   12 us [12;12]      (   3 S)
 [ 1] count:   36,  width:   28 us [24;36]      (   7 S)
 [ 2] count:    9,  width:   52 us [52;56]      (  13 S)
 [ 3] count:    1,  width:  208 us [208;208]    (  52 S)
 [ 4] count:    9,  width:   76 us [76;84]      (  19 S)
 [ 5] count:    3,  width:  104 us [104;108]    (  26 S)
 [ 6] count:    1,  width:  156 us [156;156]    (  39 S)
Pulse period distribution:
 [ 0] count:    1,  width:   12 us [12;12]      (   3 S)
 [ 1] count:   25,  width:   52 us [48;64]      (  13 S)
 [ 2] count:   13,  width:   76 us [76;80]      (  19 S)
 [ 3] count:    6,  width:  212 us [184;236]    (  53 S)
 [ 4] count:   10,  width:  108 us [104;132]    (  27 S)
 [ 5] count:    5,  width:  136 us [132;156]    (  34 S)
Level estimates [high, low]:   1250,      4
RSSI: -11.2 dB SNR: 24.0 dB Noise: -36.1 dB
Frequency offsets [F1, F2]:   13941,   5933     (+53.2 kHz, +22.6 kHz)
Guessing modulation: No clue...

signal_bsize = 131072  -      sg_index = 786432
start_pos    = 349904  -   buffer_size = 3145728
*** Saving signal to file g011_867.95M_250k.cu8
*** Writing data from 349904, len 131072

```

**Comment by slundell** [comment]
Decoder is implemented in a PR in the main project: https://github.com/merbanan/rtl_433/pull/959

**Comment by slundell** [comment]
Added new testcases. Passes my tests.

**Comment by merbanan** [comment]
@zuckschwerdt can we merge this now?

**Comment by zuckschwerdt** [comment]
Seems like quite a big chunk of files. Do we need all (unidentified folder)? I can merge and prune those extra files if that's ok? Also I need to a `ignore` file to keep the Travis CI happy.

**Comment by merbanan** [comment]
Yeah, 5-10% of the files will do.

**Pull request merged**
