### PR TITLE
Add EcoWitt WH31B samples

### PR DESCRIPTION
**Pull request by bitfliq**
Added samples for EcoWitt WH31B - very similar to EcoWitt WH31E, but with different ID codes.    Decoder used to create the output here added in https://github.com/bitfliq/rtl_433/commit/70599a9279fb58294003bfe89a21f1a4bd73a4ee
Thanks for all of your work on this project!

### CODE REVIEW

**Comment by Mindavi** [comment]
The output.txt and the csv files are not needed. Thanks for the samples!

**Comment by bitfliq** [comment]
Removed txt and csv files, updated formatting on readme

**Comment by bitfliq** [comment]
Are json files desired here if I have a working decoder?

**Comment by bitfliq** [comment]
Json files added.

**Comment by Mindavi** [comment]
I'll test this soon-ish. It's good to go other than me wanting to run this against your PR :) before merging. Thanks!

**Comment by Mindavi** [comment]
Tested and works well with the decoder, so lets move this to master. Thanks!

**Pull request merged**
