### PR TITLE
Add Oregon Scientific UVR128 UV Sensor samples

### PR DESCRIPTION
**Pull request by ovrheat**
Add Oregon Scientific UVR128 UV Sensor samples.

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Are these recorded on the default sample rate and center frequency?

**Comment by zuckschwerdt** [comment]
All is well. I'd just like to rename the files for future reference.

**Comment by ovrheat** [comment]
Ah, ok :) These are several recordings, picked up in many different times anyway... I renamed all in that way just to have some kind of order.

**Comment by zuckschwerdt** [comment]
The params are not terribly important, just nice to have. See https://github.com/merbanan/rtl_433_tests/commit/0382340

**Comment by ovrheat** [comment]
That's right. I'll keep it in mind for the next time ;)

**Pull request merged**
