### PR TITLE
tests for Alecto WS 1200

### PR DESCRIPTION
**Pull request by untergasser**
Hi,

rtl_433 is great and exactly what I need. Unfortunately it did not work out of the box with my Alecto WS 1200. I created some sample data and analyzed the format as far as I could. Reading of temperature and rain should be quite easy, but some parts which are not required (maybe checksums and some sort of day counter) remain a mystery to me. It would be great if Alecto WS 1200 could be added to rtl_433.

Best,

Andreas

### CODE REVIEW

**Comment by untergasser** [comment]
Just found the manual:
https://www.alecto.nl/media/blfa_files/WS-1200_manual_NL-FR-DE-GB_V2.2_8712412532964.pdf

**Comment by zuckschwerdt** [comment]
Looks good so far. I'll see if I can fill in what's missing.

**Comment by zuckschwerdt** [comment]
Here is [a BitBench](http://triq.net/bitbench?c=%7B95%7Dfe65a2b79201fe1460a3e452&c=%7B95%7Dfe65a2b99201ff317ea3e452&c=%7B95%7Dfe65a2b79201fe1460a3e452&c=%7B95%7Dfe65a2fd9201ffde70a3e452&c=%7B95%7Dfe65a2f39201fefb82a3e452&c=%7B95%7Dfe65a31b9801fe8b40a3e452&c=%7B95%7Dfe65a32f9801fecd96a3e452&c=%7B95%7Dfe65a3459801ff7656a3e452&c=%7B95%7Dfe65a3599801ff5c50a3e452&c=%7B95%7Dfe65a4ab9a01fee52ea3e452&c=%7B95%7Dfe65a4ad9c01fe4896a3e452&c=%7B95%7Dfe65a4af9e01fff244a3e452&c=%7B95%7Dfe65a4afa001ffd82ca3e452&c=%7B95%7Dfe65a59da001ff4486a6188c&c=%7B95%7Dfe65a59ba001fe7dbca6188c&c=%7B95%7Dfe65a563dc01ff5ca0a6188c&c=%7B95%7Dfe65a54dfa01fed420a6188c&c=%7B95%7Dfe65a5300003fe0940a6188c&c=%7B95%7Dfe65a5160203ffcceca6188c&f=PRE%3A12h%20ID%3A8h%20%3F%3A1h%20T%3A10d%20R%3A8d%20%3F%3A8h8h%20M%3A8h8h%20D%3A8h8h8h) to fiddle with the decoding.

**Comment by zuckschwerdt** [comment]
Also if you can grab messages that differ only by a single bit in the payload we can work out the checksum (perhaps CRC-16) with a [BitBench like this](http://triq.net/bitbench?c=%7B95%7Dfe65a2b79201fe1460a3e452&c=%7B95%7Dfe65a2b99201ff317ea3e452&c=%7B95%7Dfe65a2b79201fe1460a3e452&c=%7B95%7Dfe65a2fd9201ffde70a3e452&c=%7B95%7Dfe65a2f39201fefb82a3e452&c=%7B95%7Dfe65a31b9801fe8b40a3e452&c=%7B95%7Dfe65a32f9801fecd96a3e452&c=%7B95%7Dfe65a3459801ff7656a3e452&c=%7B95%7Dfe65a3599801ff5c50a3e452&c=%7B95%7Dfe65a4ab9a01fee52ea3e452&c=%7B95%7Dfe65a4ad9c01fe4896a3e452&c=%7B95%7Dfe65a4af9e01fff244a3e452&c=%7B95%7Dfe65a4afa001ffd82ca3e452&c=%7B95%7Dfe65a59da001ff4486a6188c&c=%7B95%7Dfe65a59ba001fe7dbca6188c&c=%7B95%7Dfe65a563dc01ff5ca0a6188c&c=%7B95%7Dfe65a54dfa01fed420a6188c&c=%7B95%7Dfe65a5300003fe0940a6188c&c=%7B95%7Dfe65a5160203ffcceca6188c&f=7x%20P%3A48b%20C%3A16b%20D%3A24h).

**Comment by untergasser** [comment]
Thanks for the fast response. The first two samples differ only by one bit in the payload. But I have no idea where it starts or ends:
[00] {95} fe 65 a5 8a 24 03 fe fa b0 a6 18 8c
[00] {95} fe 65 a5 88 24 03 ff cd 80 a6 18 8c

**Comment by untergasser** [comment]
How many samples are needed? I could create some by triggering the rain unit.

**Comment by merbanan** [comment]
10+ optimally but 5 should be enough to start with.

**Comment by zuckschwerdt** [comment]
It also looks like the 8 bit field after the 8 bit rain went from 0 to 1 after the wrap around, maybe rain is 16 bit little-endian?

**Comment by zuckschwerdt** [comment]
A way to work out the checksum is: note the changed bit and compute the XOR in the checksum for that bit (0xe6c0 ^ 0x7d58 = 0x9b98 here). Now remove that bit from every message by using that xor if the bit is set and unset the bit. Then look for the next single bit change and repeat. You will get a list of xor values for the bit positions. Then work out how the xor values relate to the bit positions.
(If you get an xor value for every bit you can effectively compute/verify the checksum but there will also be a way to generate all those values. For CRC it will roll and toggle some bits at each step, for a MAC/LFSR it will be a little bit more involved.)

**Comment by untergasser** [comment]
I think you are right with the rain sensor, looks like 16 bit little-endian. I will check that out by putting it under the water pipe later that day. I also recorded the readings with one bit changed (except nr. 3, with two changed bits):
{95}fe6ce4dc0601fe98c890d3a8
{95}fe6ce4dc0801ff5f9090d3a8
{95}fe6ce4da0a01feeb1c90d3a8
{95}fe6ce4dc0a01ffd20690d3a8
{95}fe6ce4dc0c01fe467c90d3a8
{95}fe6ce4dc0e01fecb0290d3a8
{95}fe6ce4dc1001ffa9e290d3a8
{95}fe6ce4dc1201ff256090d3a8
{95}fe6ce4dc1401feb0ee90d3a8
{95}fe6ce4dc1601fe3c7c90d3a8
{95}fe6ce4dc1801fffa3c90d3a8
{95}fe6ce4dc1a01ff77ba90d3a8
{95}fe6ce4dc1c01fee32890d3a8
{95}fe6ce4dc1e01fe6eb690d3a8
{95}fe6ce4dc2001fe448e90d3a8
{95}fe6ce4dc2201fec91490d3a8
{95}fe6ce4dc2401ff5daa90d3a8
{95}fe6ce4dc2601ffd02090d3a8
I am sorry, but the checksum calculations are a bit too complicated for me.

**Comment by zuckschwerdt** [comment]
No worries, this is a tricky case anyway. Easier spot if you've done it before ;) The data is good, so…
Starting at bit 15 (after 15 bits of 1) it's a CRC-8 poly 0x31 init 0 for 7 bytes. Then another checksum and the trailing 3 bytes.

**Comment by zuckschwerdt** [comment]
I can add support for this sensor in the next days. Could you cycle the battery a few times and see which bits are really part of the ID. Also if you got a variable power supply or a known flat battery you could find out where the battery_low bit is.

**Comment by untergasser** [comment]
I cycled the battery. The sensor seems to have a DCF77 due to a ferrit on it. It also sends strange messages in the first minutes, probably due to the time sync.

The battery bit responds very slow. Once set it seems to stay for a long time. It is also not easily set. The sensor powers off before the bit is set, increasing the voltage it booted up with the battery bit set up.

The pattern seems to be:
PRE: 7b Type: 4b ID: 8b BATTERY: 1b ?:1b T: 10d R:<16d ?: 8h CRC: 8h MAC: 8h DATE: 35b

Cycling the battery (*):
{95}fe7d05000001ffbc3a000000
*
{95}fe7b04e60001ffc426000000
*
{95}fe7884dc0001feecc2000000
{95}fea588203202020c4421e2d4
{95}fea588203202020c4421e2d4
{95}fea588203202020c44b0ea6c
{95}fea588203202020c468dbb1a
{95}fea588203202020c4869d310
{95}fe7884da0001ffd5a869d310
*
{95}fe6b44da0001ffda60000000
{95}fea4b4203202020c6c82d178
{95}fea4b4203202020c6e533db6
{95}fea4b4203202020c702fba12
{95}fea4b4203202020c720a1046
{95}fe6b44da0001ffda600a1046
*
{95}fe7f64da0001ffca84000000
{95}fea5f6203202020ca2100bb8
{95}fea5f6203202020ca488d0f8
{95}fea5f6203202020ca665858a
{95}fe7f64da0001ffca8465858a
*
{95}fe6744dc0001ff65e8000000
{95}fea474203202020e0253f3c2
{95}fea474203202020e042e1dca
{95}fea474203202020e060bb742
{95}fea474203202020e06a6062e
{95}fe6744dc0001ff65e8a6062e
*
{95}fe7864dc0001fe661c000000
{95}fea586203202020e680f3236
{95}fea586203202020e68ab0aaa
{95}fea586203202020e6a8728a6
{95}fea586203202020e6c6247a2
{95}fe7864dc0001fe661c6247a2
* Low batt @ 2.25 V
{95}fe6094de0001fec898000000
{95}fea4092032020210068dd276
{95}fea40920320202100869ba3c
{95}fea40920320202100a4599f8
{95}fea40920320202100c208cca
{95}fe6094de0001fec898208cca
{95}fe6094dc0001ffffcc208cca

**Pull request merged**
