### PR TITLE
Add tests for Digoo RD-R8H.

### PR DESCRIPTION
**Pull request by mhansen**
Same protocol as Nexus sensor, it seems.

### CODE REVIEW

**Comment by mhansen** [comment]
Friendly ping - any chance of a review on this?

**Comment by zuckschwerdt** [comment]
Please, if possible:
- rename (and perhaps format) the README to .md
- reduce the samples to around 5 interesting ones? (we need to watch repo size)
- crop and reduce the manual, better yet copy the interesting bits (headline?) to the readme
- record the JSON output with the current rtl_433 or `-M newmodel` (tests will fail otherwise)

**Comment by mhansen** [comment]
Done all, thx

* renamed
* reduced to 3 samples (one per channel)
* cropped manual, copied interesting bits to readme
* used new JSON output

**Comment by zuckschwerdt** [comment]
Perfect! Thanks!

**Pull request merged**
