### PR TITLE
Decoded time signal

### PR DESCRIPTION
**Pull request by untergasser**
The rain sensor has a DCF77 reciver and syncs to the station at 2:00 at night.
The time signals are decoded in folder 03.

I assume that the last bits are the checksums, but I am unable to decode them. Could you have a look? Could you point me to some information how they are calculated? Thank you!

Best,

Andreas

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
It again looks like the same CRC-8 poly 0x31 init 0x00. And then some unknown MAC.
I.e. remove the 7 bit preamble then `crc8(b, 10, 0x31, 0x00) == 0`.

**Comment by curlyel** [comment]
Hi Andreas,
just stumbled over your [https://github.com/untergasser/tempRainPi](url)
an noticed that some work have already been done in decoding the signal from the WS1200 with rtl_433.

Are you still working on this? I do have a couple of WS1200 too. Keen to get it connected via rtl_sdr ;-)
Is there some chance to get into to rtl_433? How can I support this?

Thanks,
Curlyel

**Comment by untergasser** [comment]
Hi Curlyel,
yes I do, but I am a bit stressed out at the moment. I opened an issue, as I think it is ready to add now:
https://github.com/merbanan/rtl_433/issues/973
I would have loved to send an pull request, but my time + skills were not sufficient at the moment.
Best,
Andreas

**Comment by curlyel** [comment]
Perfect - thanks! 
I've subscribed to that issue too now and offered to help with testing at least.

**Pull request merged**
