### PR TITLE
Add Lucci Air Slimline Ceiling Fan Remote

### PR DESCRIPTION
**Pull request by mcauser**

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Well documented and exhaustive test signals! Please note that there is no need to write a cutom decoder, the flex-decoder can take care of "doorbell"-style devices like simple remotes.
This should get you started:
```
rtl_433 -q -F json -R 0 -X 'lucci:OOK_PWM:340:680:800:800' -r g001_433.987M_250k.cu8
```
The signal needs a closer inspection, it does not look like just PWM, the gaps might matter too. It is not Manchester encoding like rtl_433 guesses, though.
Also note that the center frequency here is very close to the sender frequency (a slight offset is generally desirable). Take a look with e.g. http://triq.net/iqs
You might need AM demodulation to get a clear picture of the pulses, DC is hard to see. For e.g. Audacity use http://triq.net/articles/sdr-nyquist-plugin-am-decode-iq-signals

**Comment by mcauser** [comment]
Thanks for that. I guess same applies for #225 and #226

So far, it looks like:

DIP=1111, press Lights button

packet | packet | packet
------ | ------ | ------
0f c0 | 07 e0 | 07 f0
00001111 110 | 00000111 1110 | 00000111 1111
AAAA1CCC 1CC | 0AAAA1CCC 1CC | 0AAAA111 1111

1. 4x address bits xor'd
2. `1`
3. 3x command bits
4. `1`
5. 2x command bits
6. `0`
7. 4x address bits xor'd
8. `1`
9. 3x command bits
10. `1`
11. 2x command bits
12. `0`
13. 4 address bits xor'd
14. `1111111`

**Comment by zuckschwerdt** [comment]
I guess it would be an idea to split the repo between regression test-cases for the decoders and all the other interesting signals and documentation. Maybe something that can render to a wiki-like page of info.

**Comment by mcauser** [comment]
A separate repo for documentation, with a /docs served on Github pages via simple jekyll template.
Something like sig id wiki: https://www.sigidwiki.com/wiki/Category:UHF but more geared towards reverse engineering consumer grade hardware.

**Comment by rohrsh** [comment]
Hi there. I have a RH787T remote. It has 6 speed buttons, not 3. 

This chap has done work decoding it. Could his work help here? 
https://community.home-assistant.io/t/dc-ceiling-fan-rf-remote-rh787t/386621

**Comment by mcauser** [comment]
Hi @rohrsh I believe the 3 button remote is for the 3 speed AC fan and the 6 button is for the 6 speed DC fan.
I've since moved house and don't have access to these fans anymore.

**Comment by rohrsh** [comment]
Thanks for the reply. Indeed I have a DC fan with 6 speeds. 

I'm keen to make this work. Feels close! Is there anything I can do to help [zuckschwerdt](https://github.com/zuckschwerdt)? Grab some fresh recordings? I have made a few captures but I am a bit new here and can't make much sense of them. 

Console output says "Use a flex decoder with -X 'n=name,m=OOK_MC_ZEROBIT,s=296,l=0,r=800'" ... but the bits produced are the same for every button I press so I'm not convinced. 

image

I also came across this work which might be the same remote under a different brand. See: https://github.com/blejdfist/CasaFan_PIO/blob/master/lib/CasaFan/src/encoders/PayloadEncoder.cpp 

```
    // 21 bits
    // AAAA LLLLLL 1 SSS D PP CCCC
    // A = Address (4 bits)
    // L = Light level (6 bits)
    // S = Fan speed (3 bits)
    // D = Fan direction (1 bit)
    // P = Fan pattern (2 bits)
    // C = Checksum
```

**Comment by zuckschwerdt** [comment]
The OOK_MC_ZEROBIT guess would be wrong, it should be `OOK_PWM`, like in your screenshot.
You can compare the formats here: https://triq.org/rtl_433/PULSE_FORMATS.html

**Comment by rohrsh** [comment]
Thank you. Here's what I see when I run with this flex: **m=OOK_PWM,s=304,l=660,r=12000**

(and all protocols enabled in my conf file)

I pressed three different fan speed buttons: 

```
Detected OOK package	2022-11-01 22:30:07.246902
sample rate too low for protocol 198 "EnOcean ERP1"
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
time      : 2022-11-01 22:30:07.246902
model     : name         count     : 1             num_rows  : 1             rows      : 
len       : 13           data      : 83f8
codes     : {13}83f8
Modulation: ASK          Freq      : 434.0 MHz
RSSI      : -0.1 dB      SNR       : 16.4 dB       Noise     : -16.5 dB
Analyzing pulses...
Total count:   13,  width: 13.20 ms		( 3299 S)
Pulse width distribution:
 [ 0] count:    8,  width:  296 us [292;308]	(  74 S)
 [ 1] count:    5,  width:  652 us [644;660]	( 163 S)
Gap width distribution:
 [ 0] count:    5,  width:  416 us [416;428]	( 104 S)
 [ 1] count:    7,  width:  776 us [772;780]	( 194 S)
Pulse period distribution:
 [ 0] count:    1,  width:  724 us [724;724]	( 181 S)
 [ 1] count:   10,  width: 1072 us [1064;1084]	( 268 S)
 [ 2] count:    1,  width: 1436 us [1436;1436]	( 359 S)
Pulse timing distribution:
 [ 0] count:    8,  width:  296 us [292;308]	(  74 S)
 [ 1] count:   12,  width:  724 us [644;780]	( 181 S)
 [ 2] count:    5,  width:  416 us [416;428]	( 104 S)
 [ 3] count:    1,  width: 10004 us [10004;10004]	(2501 S)
Level estimates [high, low]:  15921,    368
RSSI: -0.1 dB SNR: 16.4 dB Noise: -16.5 dB
Frequency offsets [F1, F2]:   12901,      0	(+49.2 kHz, +0.0 kHz)
Guessing modulation: Manchester coding
view at https://triq.org/pdv/#AAB104012802D401A027148292929292918181818181818355
Attempting demodulation... short_width: 296, long_width: 0, reset_limit: 784, sync_width: 0
Use a flex decoder with -X 'n=name,m=OOK_MC_ZEROBIT,s=296,l=0,r=784'
pulse_slicer_manchester_zerobit(): Analyzer Device
bitbuffer:: Number of rows: 1 
[00] {14} 3e 00     : 00111110 000000

Detected OOK package	2022-11-01 22:30:07.272694
sample rate too low for protocol 198 "EnOcean ERP1"
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
time      : 2022-11-01 22:30:07.272694
model     : name         count     : 1             num_rows  : 1             rows      : 
len       : 13           data      : 83f8
codes     : {13}83f8
Modulation: ASK          Freq      : 434.0 MHz
RSSI      : -0.1 dB      SNR       : 16.5 dB       Noise     : -16.7 dB
Analyzing pulses...
Total count:   13,  width: 13.21 ms		( 3302 S)
Pulse width distribution:
 [ 0] count:    8,  width:  296 us [288;316]	(  74 S)
 [ 1] count:    5,  width:  652 us [648;660]	( 163 S)
Gap width distribution:
 [ 0] count:    5,  width:  420 us [416;424]	( 105 S)
 [ 1] count:    7,  width:  776 us [768;784]	( 194 S)
Pulse period distribution:
 [ 0] count:    1,  width:  740 us [740;740]	( 185 S)
 [ 1] count:   10,  width: 1068 us [1068;1076]	( 267 S)
 [ 2] count:    1,  width: 1444 us [1444;1444]	( 361 S)
Pulse timing distribution:
 [ 0] count:    8,  width:  296 us [288;316]	(  74 S)
 [ 1] count:   12,  width:  724 us [648;784]	( 181 S)
 [ 2] count:    5,  width:  420 us [416;424]	( 105 S)
 [ 3] count:    1,  width: 10004 us [10004;10004]	(2501 S)
Level estimates [high, low]:  15945,    354
RSSI: -0.1 dB SNR: 16.5 dB Noise: -16.7 dB
Frequency offsets [F1, F2]:   13327,      0	(+50.8 kHz, +0.0 kHz)
Guessing modulation: Manchester coding
view at https://triq.org/pdv/#AAB104012802D401A427148292929292918181818181818355
Attempting demodulation... short_width: 296, long_width: 0, reset_limit: 788, sync_width: 0
Use a flex decoder with -X 'n=name,m=OOK_MC_ZEROBIT,s=296,l=0,r=788'
pulse_slicer_manchester_zerobit(): Analyzer Device
bitbuffer:: Number of rows: 1 
[00] {14} 3e 00     : 00111110 000000

Detected OOK package	2022-11-01 22:30:07.298494
sample rate too low for protocol 198 "EnOcean ERP1"
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
time      : 2022-11-01 22:30:07.298494
model     : name         count     : 1             num_rows  : 1             rows      : 
len       : 13           data      : 83f8
codes     : {13}83f8
Modulation: ASK          Freq      : 434.0 MHz
RSSI      : -0.1 dB      SNR       : 17.2 dB       Noise     : -17.3 dB
Analyzing pulses...
Total count:   13,  width: 13.20 ms		( 3301 S)
Pulse width distribution:
 [ 0] count:    8,  width:  296 us [288;320]	(  74 S)
 [ 1] count:    5,  width:  652 us [644;660]	( 163 S)
Gap width distribution:
 [ 0] count:    5,  width:  416 us [412;428]	( 104 S)
 [ 1] count:    7,  width:  776 us [772;784]	( 194 S)
Pulse period distribution:
 [ 0] count:    1,  width:  732 us [732;732]	( 183 S)
 [ 1] count:   10,  width: 1072 us [1064;1084]	( 268 S)
 [ 2] count:    1,  width: 1432 us [1432;1432]	( 358 S)
Pulse timing distribution:
 [ 0] count:    8,  width:  296 us [288;320]	(  74 S)
 [ 1] count:   12,  width:  724 us [644;784]	( 181 S)
 [ 2] count:    5,  width:  416 us [412;428]	( 104 S)
 [ 3] count:    1,  width: 10004 us [10004;10004]	(2501 S)
Level estimates [high, low]:  15972,    303
RSSI: -0.1 dB SNR: 17.2 dB Noise: -17.3 dB
Frequency offsets [F1, F2]:   12636,      0	(+48.2 kHz, +0.0 kHz)
Guessing modulation: Manchester coding
view at https://triq.org/pdv/#AAB104012802D401A027148292929292918181818181818355
Attempting demodulation... short_width: 296, long_width: 0, reset_limit: 788, sync_width: 0
Use a flex decoder with -X 'n=name,m=OOK_MC_ZEROBIT,s=296,l=0,r=788'
pulse_slicer_manchester_zerobit(): Analyzer Device
bitbuffer:: Number of rows: 1 
[00] {14} 3e 00     : 00111110 000000

```

**Comment by LukePrior** [comment]
Hi @mcauser, I've got this same model of fan do you know of any code that I can use to transmit signals to control the fan/light?

**Comment by mcauser** [comment]
@LukePrior it's plain old ASK/OOK. Any microcontroller can TX the signal by simply toggling a pin high/low with the appropriate pauses, through a cheap 433mhz transmitter.

Each time you press a button on the remote it sends the same signal. There's no rolling codes or unique codes.
Sniff your remote's signals with an RTL-SDR using [universal radio hacker](https://github.com/jopohl/urh) to find out the signal and timings, then in code set it as a variable and loop over the bits toggling the TX pin and pausing.

If you hold down the button, you'll notice the same signal repeats a few times at a regular interval. You should do the same to make sure at least one of the signals arrive. 3 repeats is usually enough, but your mileage may vary.

Which microcontroller are you planning on using?

**Comment by zuckschwerdt** [comment]
> Sniff your remote's signals with an RTL-SDR using 

Or use `rtl_433 -S all` and https://triq.org/pdv/ to visualize the OOK. Also `rtl_433 -w file.ook file.cu8` can convert a sample to OOK text to read through ;)

**Pull request merged**
