### PR TITLE
Add test data for Conrad Pool Thermometer

### PR DESCRIPTION
**Pull request by Philippovitsch**

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Are the samples taken with default settings, i.e. 433.92M and 205k? Can you rename them to e.g. t244c_433.92M_250k.cu8 so there is no ambiguity?

**Comment by Philippovitsch** [comment]
Yes, they are taken with default settings, changed the file names, thanks.

**Comment by Philippovitsch** [comment]
Got an idea of extracting the temperature, attached a file with my thoughts.
The rest of the message are the same bits everytime, wheter I re-insert the batteries or pressing the reset button, except the last 4 bits.

[Decoding.pdf](https://github.com/merbanan/rtl_433_tests/files/1737369/Decoding.pdf)

**Comment by zuckschwerdt** [comment]
please use an issue at rtl_433 to discuss.

**Pull request merged**
