### PR TITLE
New recordings for GT-WT01 and GT-WT02

### PR DESCRIPTION
**Pull request by curlyel**
Both, GT-WT01 and GT-WT02, are not decoded by rtl_433. The current README.md shows (IMHO) some probably wrong assumptions for decoding.

I've recorded some more samples with different conditions (channels, temperatures positive/negative, button pressed, etc.) to highlight their representations in the coded rf-packet.

Folder /02/ contains recordings for GT-WT01
Folder /03/ holds the samples of GT-WT02

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Thanks! Looks good. I'll try to figure out what's wrong tomorrow.

**Comment by zuckschwerdt** [comment]
Turns out the mentioned corrections are to the docs only. The code already has that.
The real culprit are different timings. Your devices seem to be faster. To test use:
```
    .short_width   = 2500, // 3ms (old) / 2ms (new)
    .long_width    = 5000, // 6ms (old) / 4ms (new)
    .gap_limit     = 8000, // 10ms (old) / 9ms (new) sync gap
    .reset_limit   = 11000,
```
and it should mostly work. (Your environment is noisy and some of the samples don't seem to demodulate correctly.)

**Comment by curlyel** [comment]
Wow, it's working for both with the timings you mentioned:
<pre><code>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2019-02-06 13:05:11
model     : GT_WT_02 sensor                        Rolling Code: 20          Channel   : 3             Battery   : OK            Button    : 1             Temperature: 20.9 C       Humidity  : 32 %
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2019-02-06 13:07:20
model     : GT_WT_02 sensor                        Rolling Code: 20          Channel   : 3             Battery   : OK            Button    : 0             Temperature: 22.0 C       Humidity  : 33 %
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2019-02-06 13:08:14
model     : GT_WT_02 sensor                        Rolling Code: 211         Channel   : 1             Battery   : LOW           Button    : 0             Temperature: 6.7 C        Humidity  : 58 %
</code></pre>

The values are decoded correctly.
No checksum is mentioned in the output but there are some calculations in the source code:

<pre><code>
    // put last 6 bits into a number
    int checksum = ((b[3] & 1 )<<5) + (b[4]>>3);

    // accept only correct checksums, (sum of nibbles modulo 64)
    if ((sum_nibbles & 0x3F) != checksum)
        return 0;
</code></pre>

So the checksum is validated but just not printed  out - right?

> environment is noisy

Yes. ;-)

**Comment by zuckschwerdt** [comment]
Yes, there is 6 bits of checksum (nibble-wide addition with carry). I'll add that as MIC marker.
Can you compare the pictures from https://github.com/curlyel/rtl_433_tests/tree/master/tests/GT-WT-02/01 to your devices? There isn't much info but I guess it's an older revision?

**Comment by curlyel** [comment]
> Can you compare the pictures from https://github.com/merbanan/rtl_433_tests/tree/master/tests/GT-WT-02/01 to your devices?

Sure ;-)
We are talking about the same devices. One of them (the GT-WT-01) is quite old indeed. Here are my sensor to compare (hardly to read on the back side: left is GT-WT-02, right is GT-WT-01)
gt-wt01 02
gt-wt01 02-back

**Comment by curlyel** [comment]
I was looking to other versions/pictures of it:
Seems, that these sensors have been sold by Aldi in Australia too ;-)

Looks like the same timings as my two devices:

https://goughlui.com/wp-content/uploads/2013/12/Analyze-Output.png
https://goughlui.com/2013/12/20/rtl-sdr-433-92mhz-askook-decoding-of-various-devices-with-rtl_433/

**Comment by curlyel** [comment]
Decoding of the GT-WT-01/02 works good so far while using the changed timings.
Unfortunately I see some exceptions now when just enabling GT-protocol: `rtl_433 -R 25`
<pre><code>
time      : 2019-02-06 15:43:16
model     : GT_WT_02 sensor                        Rolling Code: 215         Channel   : 1             Battery   : OK            Button    : 0             Temperature: 7.6 C        Humidity  : 49 %
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2019-02-06 15:46:56
model     : GT_WT_02 sensor                        Rolling Code: 20          Channel   : 3             Battery   : OK            Button    : 0             Temperature: 23.3 C       Humidity  : 30 %
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2019-02-06 15:47:52
model     : GT_WT_02 sensor                        Rolling Code: 20          Channel   : 3             Battery   : OK            Button    : 0             Temperature: 23.3 C       Humidity  : 30 %
Async read stalled, exiting!
</code></pre>
Or another:
<pre><code>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2019-02-06 16:10:16
model     : GT_WT_02 sensor                        Rolling Code: 20          Channel   : 3             Battery   : OK            Button    : 0             Temperature: 21.7 C       Humidity  : 31 %
Segmentation fault
</code></pre>

Probably due to the noise? Could the decoder suffer from this?

**Comment by merbanan** [comment]
The segfault could be a real issue but I think it is caused by flaky hardware.

**Comment by merbanan** [comment]
Compile with debug symbols and get a gdb back trace.

**Comment by zuckschwerdt** [comment]
I've enhanced the PPM demod and modified the timings. All samples decode fine now!

**Comment by curlyel** [comment]
Amazing! You're so quick. Thank's a lot! It appears to be really reliable now. It catches (almost?) all packets from the GT-WT-xx. I have a successful decode every few seconds (aprx. five times better than before!!!!):

<pre><code>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2019-02-06 17:50:46
model     : GT-WT02      ID Code   : 215
Channel   : 1            Battery   : OK            Button    : 0             Temperature: 1.9 C        Humidity  : 69 %          Integrity : CHECKSUM
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2019-02-06 17:51:04
model     : GT-WT02      ID Code   : 20
Channel   : 3            Battery   : OK            Button    : 0             Temperature: 21.2 C       Humidity  : 30 %          Integrity : CHECKSUM
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2019-02-06 17:51:36
model     : GT-WT02      ID Code   : 215
Channel   : 1            Battery   : OK            Button    : 0             Temperature: 1.9 C        Humidity  : 69 %          Integrity : CHECKSUM
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2019-02-06 17:52:00
model     : GT-WT02      ID Code   : 20
Channel   : 3            Battery   : OK            Button    : 0             Temperature: 21.2 C       Humidity  : 30 %          Integrity : CHECKSUM
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2019-02-06 17:52:26
model     : GT-WT02      ID Code   : 215
Channel   : 1            Battery   : OK            Button    : 0             Temperature: 1.8 C        Humidity  : 69 %          Integrity : CHECKSUM
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2019-02-06 17:52:56
model     : GT-WT02      ID Code   : 20
Channel   : 3            Battery   : OK            Button    : 0             Temperature: 21.3 C       Humidity  : 30 %          Integrity : CHECKSUM
</code></pre>

Even if it's a dumb question: Where to put `-g` option for debug symbols? I'd love to let it run for a while in gdb if it helps finding some potential flaw.

**Comment by zuckschwerdt** [comment]
Turns out the PPM demod was somewhat too picky, good thing you found that problem with the timing so I needed to take a close look at things ;)
If you build with CMake (you really should):
```
mkdir Debug
cd Debug
cmake -DCMAKE_BUILD_TYPE=Debug ..
make
```
CMake Debug builds default to include symbols (`-g`) other wise you can tweak the CMakeLists.txt.

**Pull request merged**
