### PR TITLE
Submitting some more Digitech XC-0324 .cu8 samples

### PR DESCRIPTION
**Pull request by Geoff99**
Hi,

Fingers crossed that I haven't messed up the `git` processes too badly while preparing this pull request.

I am hoping to add some additional .cu8 samples to the existing (Digitech) XC-0324 temperature sensor entry in this tests repository.  

They are in 3 separate numbered sub-directories (02/ 03/, and 04/).  For neatness I have also moved the existing .cu8 files to a 01/ sub-directory.

I have included `ReferenceValues.csv` files, containing the correct values corresponding to each .cu8 sample file.

Further details are included in my updates to the `tests/XC-0324/readme.md` file.

I have developed a prototype device decoder for the XC-0324 sensor (with many thanks to the suite of examples already available in the rtl_433 repository) and intend to submit that for consideration and review as soon as I have tidied it up.

If I need to do anything else to submit this test data in a way that is not too burdensome for you, please let me know and I'll be happy to oblige.  I've used `git` a bit, but often mess things up :-(

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Thanks. I guess I'll have a look and pick this apart, there are so many files and "Bad transmission". I'd say it's overkill for a single device to have 230 samples. Are there specific things you want to highlight with the 02, 03, 04 files?

**Comment by Geoff99** [comment]
Hi @zuckschwerdt 
Please don't waste your time picking this apart.  I'll thin the samples down considerably and let you know when it's ready for your attention again.

The 02, 03 and 04 files just represent 3 sets of experiments (fiddling with gain and frequency parameters) while I was in debug/decipher mode.  I've been batch processing the whole suite of files in each set, creating one "csv" formatted line per sample file, and saving the set in a single file (using an approach similar to but not exactly the same as suggested in the comments in https://github.com/merbanan/rtl_433/issues/748).  Then I opened the csv file in a spreadsheet program, pasted in the true values recorded when the samples were taken, sorted by true value, and looked for patterns.  Removing files would have made it much more fiddly to paste the true values onto the right line (I went through this cycle **lots** of times, as all this was very new to me).

The bad transmissions were (mostly) from the sensor I had put in the freezer as it warmed up, and included negative degree C temperatures.  Initially I had hoped that once I was further down the track with deciphering the protocol I would be able to figure them out and retrieve the temperatures (after all the XC-0322 monitor had read them OK) but eventually I concluded that they simply hadn't been received well enough on my rtl-sdr dongle (looking at those specific samples in Audacity shows they are pretty badly distorted!).

Apologies for not thinking through what would be useful longer term as a regression test set of samples.  I'll update my local repository, push the changes, and get back to you.

**Comment by zuckschwerdt** [comment]
Thanks! The consideration here is that every sample commited grows the repo size forever, even if we later remove them. So I like to get a quality set of samples right away.
Try http://triq.net/iqs to visualize the samples. You should be able to spot what's worth keeping/investigating.

**Comment by Geoff99** [comment]
Hi @zuckschwerdt 
(After a few tussles with git on my local repository) I have trimmed the pull request to only 40 new samples, in two new sub-directories /02 and /03.  

I haven't changed the 01 subdirectory  - it doesn't "belong" to me, and anyway, the samples are already there :-)

The 02 directory contains only "good" values with temperature points that I found useful when deciphering the bitbuffer 

* some low temps, 
* some high temps, 
* a few near a magic value of 11.2 C (=-40 C + (512/10), which is where the 3rd nibble of the temperature bytes starts to be needed), and 
* a run (from 14.0 - 16.0 C in 0.1 C steps) which was helpful in discovering that the natural steps as transmitted were 0.1 C, and that the temperature bit pattern is transmitted least significant bit first.

 The 03 directory contains "useable" samples, ie temperature and id can be extracted from the package, but at least one of the 3 repeat messages contains a parity/checksum error, which was useful for discovering the checksum/parity bit algorithm.

If that's still too many **just say**, and I will trim them back some more (it's easy enough for me to do, just give me a hint about what is a reasonable number to include).

Once that's done, I'll finish tidying up my prototype decoder, and submit a pull request for that to rtl_433.  (It's really quite trivial decoder - **in hindsight** - since there are really only 4 fields (sync/preamble, id, temperature and checksum - but this was my first attempt at decoding an rtl_433 package and I had a lot of learning to do, and fun to experience :-) along the way).

PS Most of my decoder is related to debug output that I can run in batch mode to produce csv files with one line per sample that can easily be manipulated (eg sorted into true temperature order) in a spreadsheet.  Plus lots of comments.  Are you OK with that as a style for a decoder ? (it's as close as I can get to a tutorial for my future self about how to set about reverse engineering a new device) - or do you prefer a clean minimal "I know what's going on, so I just do the decoding" approach for a new device?  I am happy to conform with whatever fits best with this very neat project!

**Comment by zuckschwerdt** [comment]
Manual merge won't keep the author attribution. Can you try
```
git checkout master
git pull
git checkout extra-xc0324-samples
git rebase master
git push -f
```

**Comment by Geoff99** [comment]
Hi @zuckschwerdt 
I finally untangled the git mess I had on my local repository, and applied the rebase as per your instructions above.  Hopefully the pull request merge will work OK now.

(I think my local git problem arose because my local working repository is on a Windows file system.  Anyway, for reasons that elude me, git thought I had changed **all** file permission from 0644 to 0755, and wouldn't let me complete pull requests or even change branches until I had saved my *work* -  eventually I discovered `git config core.fileMode false`, after which it only took a few moments to bring everything up to date :-) )

**Comment by zuckschwerdt** [comment]
Line endings are always a mess, yes.
Somehow the tests/ambient_weather/04/  files are still modified?

**Comment by Geoff99** [comment]
Aaargh! My apologies @zuckschwerdt 

I was so excited about finally finding out how to use `config core.fileMode false` to stop git telling me I had changed **every file** in the whole repository, that I forgot to do a final compare check between my pull request and your master branch.

I think my pull request is well behaved now, in the sense that it only changes or adds files in the tests/XC-0324 sub-directory.  I've reverted my unintended changes in the tests/ambient_weather/04 directory by checking out the relevant files from your master branch and committing the corrected files in my pull request branch.

Apologies also for the messy commit history that has eventuated as a consequence of my sequence of "not quite right" attempts.  I hope this is OK now :-) , but if it's not I think I will close this pull request, clone myself a clean rtl_433_tests repository, (very carefully) create ONLY those changes that are essential in a new branch, and submit a new pull request on the clean copy.

**Comment by zuckschwerdt** [comment]
Thanks. Multiple commits are fine, squash merge will roll them into a single merged commit.

**Pull request merged**
