### PR TITLE
Add LaCrosse TX34 rain gauge device

### PR DESCRIPTION
**Pull request by rey42**

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
The `.sr` should not be merged, otherwise looks good.

**Comment by zuckschwerdt** [comment]
Oh, less than a kB? That's not the file we generate with e.g. `rtl_433 -w g001_868.3M_1000k.sr g001_868.3M_1000k.cu8` then, right?

**Comment by rey42** [comment]
This is the file generated by rtl_433 but without the analog parts - useful for protocol example and analyzis

**Comment by merbanan** [comment]
Tiny files are ok.

**Comment by zuckschwerdt** [comment]
> Tiny files are ok.

Agreed. Wouldn't the .ook file be more interesting though? E.g. `rtl_433 -f 868.3M -s 1000k -w g001_868.3M_1000k.ook g001_868.3M_1000k.cu8`
See the output (with added slicer hint) here: https://triq.org/g001_868.3M_1000k.ook
Get the file and drop on https://triq.org/pdv/ to see:

screenshot

**Pull request merged**
