### PR TITLE
Add data for Burnhard BBQ Thermometer

### PR DESCRIPTION
**Pull request by fetzerch**
This adds sample/test data for a [Burnhard BBQ thermometer](https://www.burnhard.de/zubehoer/uebersicht/grillzubehoer/digitales-bbq-thermometer-inkl.-4-sonden-943174).

I've been able to successfully decode a large part of the message. Here are my findings with `rtl_433 -X 'n=burnhardbbq,m=OOK_PWM,s=240,l=484,r=848,g=0,t=0,y=840,invert'`:

A message consists of 3 parts - one for each of the three thermometer probes.
Each part consists of 3 rows with 81 bits of data. Except for the last bit, each of the rows is the same.

```
time      : @0.151160s
model     : burnhardbbq  count     : 3             num_rows  : 3             rows      : 
len       : 81           data      : 1f2000000005b024d79b0,   <PROBE1
len       : 81           data      : 1f2000000005b024d79b0,   <PROBE1
len       : 81           data      : 1f2000000005b024d79b0    <PROBE1
codes     : {81}1f2000000005b024d79b0, {81}1f2000000005b024d79b0, {81}1f2000000005b024d79b0
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : @0.604772s
model     : burnhardbbq  count     : 3             num_rows  : 3             rows      : 
len       : 81           data      : 1f21000000123824daa48,   <PROBE2 
len       : 81           data      : 1f21000000123824daa48,   <PROBE2
len       : 81           data      : 1f21000000123824daa40    <PROBE2
codes     : {81}1f21000000123824daa48, {81}1f21000000123824daa48, {81}1f21000000123824daa40
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : @1.038852s
model     : burnhardbbq  count     : 3             num_rows  : 3             rows      : 
len       : 81           data      : 1f22009052441425e51e0,   <PROBE3
len       : 81           data      : 1f22009052441425e51e8,   <PROBE3
len       : 81           data      : 1f22009052441425e51e8    <PROBE3
codes     : {81}1f22009052441425e51e0, {81}1f22009052441425e51e8, {81}1f22009052441425e51e8
```

An exemplary analysis of the last row (`1f22009052441425e51e8`) yields:

```
1f 22 00 9052 44 1425e5 1e 8
AA SD ?? TTTT mt XXYXYY CC ?

AA   device code (changes when battery is removed)
S    settings, 2=Celsius, 0=Fahrenheit (there might be more data coded here, like battery empty or alarm)
D    thermometer probe number (0, 1, 2 or 8, 9, a - I've seen that the highest bit is sometimes set, but i couldn't spot a pattern)
??   always 0 so far
TTTT the timer, bcd coded. 90:52 (also here the highest bit of the minute is sometimes set)
m    meat (0=free, 1=beef, 2=veal, 3=pork, 4=chick, 5=lamb, 6=fish, 7=ham)
t    taste (0=rare, 1=medium rare, 2=medium, 3=medium well, 4=well done, 5 when m is set to free)
XXX  target temperature (-500, /10), 0x514 -> 1300-500=800 / 10 = 80   (12 bits, it's a little strange that the highest nibble is intermixed with the next field)
YYY  current temperature (like above), 0x2e5 -> 741-500=241 / 10 = 24,1
CC   probably a yet unknown CRC
?    a single bit - this is the only bit that is different in one part of 3 equal messages
```

Before starting to implement it, it would be great if someone more experienced could help out:
- 81 bits per row, with the last sometimes being 1 or 0 looks strange to me. Is the demodulation correct? I first thought it could be 9 bits per byte (with the last being a parity), but then the fields are no longer on byte/nibble boundaries.
- Regarding the CRC, I tried [crc reveng](https://reveng.sourceforge.io/) which didn't help so again I'm wondering if the demodulation might not be right.

Thanks a lot for your input!

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
As the bytes align so nicely the last bit is very likely an artifact of the coding.
The checksum doesn't look like a CRC, it could be a digest. Can you collect more unique codes? Juste paste lines of
```
{81}1f22009052441425e51e0
```
or
```
1f22009052441425e51e
```

**Comment by fetzerch** [comment]
Thanks! Does that help?

```
e22a00000005e80300b6
1f2200000005e80300f4
e20000000005e80300f5
e20100000005e8030040
e20200000005e80300ae
1f0000000005e80300ea
1f0100000005e803005f
1f0200000005e80300b1
e22a00000005e80300b6
e22a00000005e823dd4b
e22a00000005f223e09a
e32a00000005e833085c
e22a00000005f4010010
e22a00000005fe01000b
e22a0000000508020091
e22a00000005120200b2
e22a000000051c0200a7
e22a00000005260200f4
e22a00000005300200c5
e22a00000005f80200c8
e22a00000005020300cc
e22a000000050c0300d9
e22a000000052a0300a0
e22a000000053403008d
e22a000000057404008e
e22a00000005f40600f3
e22a000000057c0b0023
e22a00000005ac0d00af
e20a00000005e80300f3
e22a00000005e80300b6
```

**Comment by zuckschwerdt** [comment]
It does. Looks like a reverse Galois LFSR with bytes reflected (which is rather uncommon) but then gen of 31 and key of f4 look as expected.

**Comment by fetzerch** [comment]
Thanks much! It seems to work with `lfsr_digest8_reflect(b, 9, 0x31, 0xf4) == b[9]`.

**Pull request merged**
