### PR TITLE
Intelbras XAS_4010_Smart updates

### PR DESCRIPTION
**Pull request by augustodinizl**
With the extremely helpful guidance from @zuckschwerdt , i think it's right now...

Tks!!

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Your other intelbras PR is already merged. And since this is on `master` and not a feature branch the merge would be complicated. Fastest way should be:
- move your intelbras files to safety somewhere
- `git reset --hard 8cddb92`
- `git pull upstream master`
- move your safed files back and do a new commit
- `git push -f`

**Comment by augustodinizl** [comment]
Changes done

**Comment by merbanan** [comment]
This PR has conflicts. I can not merge it.

**Comment by augustodinizl** [comment]
Conflicts solved, sorry

**Comment by zuckschwerdt** [comment]
Wouldn't it be nice to squash those 27 commits into a single commit? That aside, the hardware description is exemplary!

**Comment by merbanan** [comment]
Next time don't squash all commits. The TPMS json files belong in their own commit.

**Comment by augustodinizl** [comment]
ops, my bad... sorry again


2017-07-17 19:20 GMT-03:00 Benjamin Larsson <notifications@github.com>:

**Pull request merged**
