### PR TITLE
Corrected data samples

### PR DESCRIPTION
**Pull request by fraschizzato**

### CODE REVIEW

**Comment by merbanan** [comment]
Hi, this PR has conflicts. Please address this and resend.

**Comment by fraschizzato** [comment]
Previous data was wrong or unusable, that commit is a "new start point" with good samples and new readme. Previous commit is totally unusable .Conflicts are between old (wrong) data and new

**Comment by merbanan** [comment]
The commit still conflicts and I can't directly merge it. These files are conflicting.

tests/urmetEasyRead/01/gfile041.data
tests/urmetEasyRead/02/gfile046.data
tests/urmetEasyRead/readme.md

**Comment by zuckschwerdt** [comment]
Can you `git reset --soft HEAD~3`, then re-add the samples, commit and `git push -f`?

**Pull request merged**
