### PR TITLE
SQMfan: samples, writeup, FCC docs, manual

### PR DESCRIPTION
**Pull request by dankamongmen**
SQMCoLtd of Taipei makes fan remote controllers used by several major manufactures, including Minka-Aire and Hampton Bay. The remote speaks ASK on 303.866MHz. I've analyzed the protocol and broken out a flex decoder for it (I'm working on a rtl_433 device, but having problems getting my code picked up there).

Included are samples from all six controls, the user manual from a Minka-Aire, the FCC testing documents for the remote control, and my writeup, including a complete protocol breakdown.

### CODE REVIEW

**Comment by dankamongmen** [comment]
@zuckschwerdt et al, any love for this?

**Comment by zuckschwerdt** [comment]
This is still on hold because the files are rather big. We need to keep the repo lean. For a 330 µs pulses signal the default 250k should be enough. I guess I need to downsample by 40 (10M to .25M).

**Comment by dankamongmen** [comment]
@zuckschwerdt happy to let you do it, but if it'll speed things up, I'll figure out how exactly to do so and try it myself.

**Comment by zuckschwerdt** [comment]
I went ahead and just resampled with `sox`. Used 1024k to keep some quality. Happy to merge a PR if you want to contribute the `conf` file to decode this. See e.g. https://github.com/merbanan/rtl_433/blob/master/conf/chungear_bcf-0019x2.conf for something similar.

**Pull request merged**
