### PR TITLE
Add new transmitter

### PR DESCRIPTION
**Pull request by Tresett**
Weather station name: misol
Samples loaded too

misol-weather_station

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Did you record this at exactly `-f 433920000` (the default) at the default sample rate (250000)?
What are the (approximate) reading for these samples?

**Comment by Tresett** [comment]
1. No, rtl_433 -a -t, 
2. Another hardware show -0.6C

**Comment by zuckschwerdt** [comment]
Thanks!

**Comment by Tresett** [comment]
Temp is down at 0.2
Do you need new records?

**Pull request merged**
